### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by etzl**

### CODE REVIEW

**Comment by dbaluta** [comment]
@etzl thanks for your patch. We should not edit the generated html files but the text rst files. In your case please edit this file:

https://github.com/linux-kernel-labs/linux/blob/master/Documentation/teaching/lectures/syscalls.rst

then our scripts will build the docs and generate html file.

**Comment by etzl** [comment]
Ok, will do.
I have other changes too, maybe it's better to close this PR and open another?

**Comment by dbaluta** [comment]
Yes, let me close it.

**Comment by etzl** [comment]
I didn't understand that it was another project. I'm new to this, have I got this right?
I'll fork that project, make the changes to the files (*.rst) and make a pull request to that project?

**Comment by dbaluta** [comment]
Yes, exactly make a fork of https://github.com/linux-kernel-labs/linux then create a PR with your changes. You have rights to create a PR on this tree.

Let me know if there is still something unclear.

**Pull request closed without merging**
